drop table if exists PUB_ENTTYPE;
create table PUB_ENTTYPE(
	ID NUMBER(22) not null ,

	PARENTENTTYPE NUMBER(22),

	CREATOR NUMBER(22),

	ENTTYPENUM VARCHAR2(30),

	ENTTYPENAME VARCHAR2(30),

	SOURCEID VARCHAR2(30),

	GROUPID NUMBER(22)
);
