drop table if exists CP_COMPLAINTPRODUCT;
create table CP_COMPLAINTPRODUCT(
	ID NUMBER(22) not null ,

	VALIDITYDATE VARCHAR2(10),

	MANUFACTURER VARCHAR2(30),

	LASTUPDATETIME DATE(7),

	DATEOFMANUFACTURE VARCHAR2(10),

	SPEC VARCHAR2(30),

	OPERATOR VARCHAR2(10),

	TEMP1 VARCHAR2(80),

	ISIMPORT VARCHAR2(5),

	APPROVAL VARCHAR2(20),

	PRODUCTCHANNEL VARCHAR2(10),

	PRODUCT VARCHAR2(30),

	BATCH VARCHAR2(20),

	TEMP2 VARCHAR2(80),

	PRODUCTTYPE VARCHAR2(5)
);
